"""Capture real GUI screenshots (demo fixtures, no personal feeds / PII)."""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from PIL import ImageGrab  # noqa: E402

from morning_digest.app import UltimateNewsApp  # noqa: E402
from morning_digest.collector import collect_news  # noqa: E402
from morning_digest.demo_data import DEMO_FEED_URLS  # noqa: E402
from morning_digest.prompts import build_prompt, empty_collector_message, get_template  # noqa: E402

OUT_DIR = ROOT / "docs" / "screenshots"


def _grab(app: UltimateNewsApp, path: Path) -> None:
    app.update_idletasks()
    app.update()
    # Ensure window is mapped and on-screen
    app.deiconify()
    app.lift()
    app.focus_force()
    app.update()
    x = app.winfo_rootx()
    y = app.winfo_rooty()
    w = app.winfo_width()
    h = app.winfo_height()
    # Small padding for window chrome on Windows
    bbox = (x, y, x + w, y + h)
    image = ImageGrab.grab(bbox=bbox)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, format="PNG")
    print(f"saved {path} ({image.size[0]}x{image.size[1]})")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        cfg = Path(tmp) / "news_config.json"
        app = UltimateNewsApp(config_path=cfg)
        app.geometry("1200x850")
        app.update()

        # 1) Empty / onboarding state
        app.textbox.delete("1.0", "end")
        app.textbox.insert("1.0", empty_collector_message())
        app.status_lbl.configure(text="Pronto")
        app.after(400, lambda: None)
        app.update()
        _grab(app, OUT_DIR / "01-collector-empty.png")

        # 2) Demo digest (same pipeline as DEMO OFFLINE)
        items, errors = collect_news(DEMO_FEED_URLS, demo=True)
        prompt = build_prompt(items, get_template("Padrão"))
        app.textbox.delete("1.0", "end")
        app.textbox.insert("1.0", prompt)
        app.status_lbl.configure(text=f"Demo! {len(items)} notícias" + (f" · {errors} falhas" if errors else ""))
        app.hint_lbl.configure(text=f"{len(app.current_feeds)} feeds ativos")
        app.update()
        _grab(app, OUT_DIR / "02-collector-demo.png")

        # 3) Settings tab
        app.tabview.set("Configurações")
        app.include_entry.delete(0, "end")
        app.include_entry.insert(0, "python, mercado")
        app.exclude_entry.delete(0, "end")
        app.exclude_entry.insert(0, "BBB")
        app.status_lbl.configure(text="Configurações")
        app.update()
        _grab(app, OUT_DIR / "03-settings.png")

        app.destroy()

    manifest = OUT_DIR / "MANIFEST.md"
    manifest.write_text(
        "\n".join(
            [
                "# Screenshot manifest",
                "",
                "Generated by `scripts/capture_screenshots.py` from the live CustomTkinter window.",
                "Content uses **demo fixtures only** (no personal `news_config.json`, no live RSS PII).",
                "",
                "| File | Scene |",
                "|---|---|",
                "| `01-collector-empty.png` | Empty / onboarding collector state |",
                "| `02-collector-demo.png` | DEMO OFFLINE digest result |",
                "| `03-settings.png` | Settings: feeds + keyword filters |",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print("done")


if __name__ == "__main__":
    main()
